### ISSUE TITLE
"class not found" using com.android.tools.build:gradle:1.5.0

### ISSUE THREAD

**Issue by tehras** [robospock/RoboSpock#57] opened 2016-01-08 18:26 UTC
This is pretty intermittent, is anyone else running into the same issues?

**Comment by tehras** [comment] 2016-01-08 18:59
Oops i guess this is the groovy-android-gradle plugin's fault - https://github.com/groovy/groovy-android-gradle-plugin/issues/61

**Comment by pjakubczyk** [comment] 2016-01-11 09:12
usually compile issues are caused by the groovy plugin.

closing ticket. thx

**Closed as completed by pjakubczyk** 2016-01-11 09:12 UTC
